version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - /home/enf-dev1/work/weather_system_exchange/data/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - /home/enf-dev1/work/weather_system_exchange/data/pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data: 
  pgadmin_data: 